<link href='http://fonts.googleapis.com/css?family=Alegreya+Sans' rel='stylesheet' type='text/css'>
<div class="row" style="background-color:#fff">



<div style="background-color:#fff">

	<div class="banner container">

		<?php echo $this->getChildHtml('topLinks')?>	

	</div>	

</div>

</div>



<div class="row" style="background-color:#e3e3e3">

<div class="container">

<div class="logo-head">

<div class="col-md-2">

	<div class="logo pull-left">

		<a href="<?php echo $this->getUrl(''); ?>">

		<img src="<?php echo $this->getLogoSrc(); ?>"/>

		</a>

	</div>	

	

</div>



<div class="col-md-10"> 

<div class="pull-right" style="padding-top:18px;">

	<?php echo $this->getChildHtml('topSearch') ?> 

</div>



</div>

</div>

</div>

</div>



<!--Menu Section -->

<div class="row" style="background-color: #c82727;">

<div class="container">

  <?php //echo $this->getChildHtml('topMenu'); ?>
  
  <?php echo $this->getChildHtml('megaMenu');?>

</div>

</div>