<div class="container"><div  class="services-new"><div  class="l-services"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('moneyback')->toHtml(); ?> </div>

<div class="r-services"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('additionalservices')->toHtml(); ?></div>
<div class="buttons-set">
                    <a title="<?php echo $this->__('sing Up for new Deals') ?>" class="button" href="<?php Mage::getBaseUrl();?>customer/account/create/ "><span><span><?php echo $this->__('Sign Up') ?></span></span></a>
                </div>
</div></div>
