<hr>
<section class="subs-test-frame">
<section class="container">
<div class="row">
<section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="row">
<article class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
<div class="subs-box">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('newsletter')->toHtml(); ?>
</div>
</article>
<article class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
<div class="test-box">
<?php echo $this->getLayout()->createBlock('testimonialmanager/testimonials')->setTemplate('testimonialmanager/testimonials_box.phtml')->toHtml(); ?>
</div>
</article>
</div>
</section>
</div>
</section></section>