<!DOCTYPE html>
<html lang="en">
<head>
<!--<link href='http://fonts.googleapis.com/css?family=Bad+Script' rel='stylesheet' type='text/css'>-->
<?php echo $this->getChildHtml('head');?>
</head>
<body>

	
	<!-- Header part -->
	<div class="col-md-12">
	<?php echo $this->getChildHtml('header');?>
	</div>	
	


	<div class="col-md-12 slider-banner">
	</div>

	
	<div class="container">
	<?php echo $this->getLayout()->createBlock('customblocks/customblock')->setTemplate('customblocks/customblock.phtml')->toHtml(); ?>
	<br/>
	<?php echo $this->getChildHtml('content');?>
	<br/>
	<?php echo $this->getLayout()->createBlock('customblocks/customblock')->setTemplate('customblocks/bottomblock.phtml')->toHtml(); ?>
	</div>
	
	<!--Footer part-->
	<div class="footer">
		<div class="col-md-12">
	  		<?php echo $this->getChildHtml('footer');?>
	  	</div>
	</div>

</body>

</html>