<div class="row">
<ul class="nav nav-tabs" id="myTab">
    <?php $i = 0; ?>
    <?php foreach ($this->getTabs() as $_index => $_tab): ?>
        <?php if($this->getChildHtml($_tab['alias']) && strlen(strip_tags(trim($this->getChildHtml($_tab['alias']))))>0): ?>
            <?php
                $tab_title = $_tab['title'];
                $tab_is_custom = strpos($_tab['alias'], 'custom');
                $tab_is_cms= strpos($_tab['alias'], 'cms');
                if($tab_is_custom === 0){
                    $tab_is_tmp_id =  substr($_tab['alias'], 6);
                    $tab_is_custom_id = (!empty($tab_is_tmp_id)) ? $tab_is_tmp_id : '';
                    $tab_title = Mage::getStoreConfig('fed_tabs/custom/customtabname'.$tab_is_custom_id);
                } elseif($tab_is_cms === 0) {
                    $tab_is_tmp_id =  substr($_tab['alias'], 3);
                    $tab_is_custom_id = (!empty($tab_is_tmp_id)) ? $tab_is_tmp_id : '';
                    $tab_title = Mage::getStoreConfig('fed_tabs/customcms/tabnamecms'.$tab_is_custom_id);
                }

            ?>
            <li>
			<a href="#product_tabs_<?php echo $_tab['alias'] ?>_contents" data-toggle="tab" <?php echo !$i  ? 'class="active first"' : '' ?>><?php echo $tab_title; ?></a></li>
	    <?php $i++; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<div class="tab-content collateral-box" >
    <?php foreach ($this->getTabs() as $_index => $_tab): ?>
        <?php if($this->getChildHtml($_tab['alias'])): ?>
            <div  id="product_tabs_<?php echo $_tab['alias'] ?>_contents" class="tab-pane"><?php echo $this->getChildHtml($_tab['alias']); ?></div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	alert('hello');
})
$('#myTab a:first').tab('show')
</script>
