<?php $testimonials = $this->_getSidebarCollection(); ?>
<?php $i = 0;?>
<?php //if ($testimonials->count() > 0): ?>
<script language="javascript" type="text/javascript">
	$j(document).ready(function(){
		$j('.bxslider').bxSlider({
			auto: true,
			speed: 500,
			controls: false,
			mode: 'fade',
			pager: false
			//autoControls: true
		});
	});
</script>
    <?php if($testimonials->count() > 0) { ?>
    	<ul class="bxslider">
		<?php foreach ($testimonials as $testimonial): ?>
			<li>
				
				<span class="img"><img src="<?php echo Mage::getBaseUrl('media'); echo $testimonial->getTestimonialImg()?>" alt="<?php echo $testimonial->getTestimonialName(); ?>" title="<?php echo $testimonial->getTestimonialName(); ?>" /></span>
				<div class="text-box">
				<h2><?php echo $this->__('Testimonials') ?></h2>
                <div class="rating-box"><div class="rating" style="width:<?php echo ceil($testimonial->getRatingSummary() * 20) ?>%;"></div></div>
				<div class="testimonial_sidebar_text"><p>&ldquo;<?php echo substr($testimonial->getTestimonialText(), 0, 300); ?>&rdquo;&nbsp;...&nbsp;<a href="<?php echo $this->getUrl('testimonials'); ?>"><?php echo $this->__('more'); ?></a></p>
				<span class="author"><?php echo $testimonial->getTestimonialName(); ?></span>
				</div>
				</div>
			</li>
		<?php endforeach; ?>
        </ul>
    <?php } else { ?>
        <p class="testimonial_sidebar_text"><?php echo $this->__('Hey!! How did you find my site and my products? Please leave your valued feedback here to make us serve you better.');?></p>
    <?php } ?>
		<div class="actions1">
		<?php if($testimonials->count() > 0) { ?>
		    <a href="<?php echo $this->getUrl('testimonials'); ?>"><?php echo $this->__('View All Testimonials'); ?></a>
		<?php } else { ?>
		    <a href="<?php echo $this->_getWriteUrl()?>"><?php echo $this->__('Write Testimonials'); ?></a>
        <?php } ?>
		</div>
<?php //endif;?>