<!DOCTYPE html>

<html lang="en">

<head>

<?php echo $this->getChildHtml('head');?>	

</head>

<body>	

	<!-- Header part -->

	<div class="col-md-12">

	<?php echo $this->getChildHtml('header');?>

</div>

	<?php 
if( Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && 
Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' ) { /* if is home page */?>	
	<?php echo $this->getLayout()->createBlock('customblocks/mainblock')->setTemplate('customblocks/mainblock.phtml')->toHtml(); ?>
	<?php } ?>



	<?php echo $this->getChildHtml('after_body_start') ?>

<div class="container">

	<div><?php echo $this->getChildHtml('breadcrumbs') ?></div>
		

			<div class="col-md-9">	

			<?php echo $this->getChildHtml('global_messages') ?>			

			<?php echo $this->getChildHtml('content');?>			

			</div>

			<div class="col-md-3">

			<?php

			if($this->getChildHtml('right')){

			echo $this->getChildHtml('right');	
			
			?>
			<img style="margin-top: 10px" src="<?= $this->getSkinUrl('images/right_side.png');?>	"/>		
			
			<?php

			}else{

				echo 'No';

			}

			  ?>	

			</div>
			
		</div>	
		
		
			<?php 
if( Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && 
Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' ) { /* if is home page */?>	
	<?php echo $this->getLayout()->createBlock('customblocks/customblock')->setTemplate('customblocks/brandblocks.phtml')->toHtml(); ?>
	<?php } ?>	
	
	<div class="container">
	<?php 
if( Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && 
Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' ) { /* if is home page */?>	
	<?php echo $this->getLayout()->createBlock('customblocks/customblock')->setTemplate('customblocks/bottomblock.phtml')->toHtml(); ?>
	<?php } ?>
	</div>

	

	<!--Footer part-->

<div class="footer">

	<div class="col-md-12">	

	  <?php echo $this->getChildHtml('footer');?>

	</div>

</div>

</body>



</html>