<?php 
$enable=Mage::getStoreConfig('customblocks_options/blocksettings0/block_select0');

$link= Mage::getStoreConfig('customblocks_options/blocksettings0/block_link0');
$image=Mage::getStoreConfig('customblocks_options/blocksettings0/block_image0');
$url=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
		$a= $url.$image;

?>
<style>
	.slide{
	width:100%;
	height:500px;
	margin-bottom: 20px;
	background:url('<?php echo $a;?>') center center no-repeat;
	}
</style>
<?php if($enable==1){?>
<div class="col-md-12 slide"></div>
<?php } ?>