 <h1><span><?php echo "Popular Series" ?></span></h1>
<br>
<?php
$n=0;
$children = Mage::getModel('catalog/category')->getCategories(2); // put your main root category id here
echo '<section class="container">
		<div class="row">
			<section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<ul class="prod-list products-grid products-grid--max-5-col new-ull">';
foreach ($children as $category):
if($n<=5)
{
	$n++;
}
else
{
	break;
}
$category=Mage::getModel('catalog/category')->load($category->getId());

?>
<?php if($category->getName()!="home")
{
?>
<li class="item last">
<div class="pop-box"><span class="img"><a href="<?php echo $category->getUrl()?>" ><img src="<?php echo Mage::getBaseUrl('media')?>catalog/category/<?php echo $category->getThumbnail() ?>"><span class="see-all-btn">See All</span></span></a>
<?php
echo '<h3 class="product-name"><a href="' . $category->getUrl() . '">' .  $category->getName() . '</a></h3></div></li>'; 
}
?>

<?php 
/*$children = Mage::getModel('catalog/category')->getCategories($category->getId());
foreach ($children as $category):
$category=Mage::getModel('catalog/category')->load($category->getId());
echo '<li><a href="' . $category->getUrl() . '">' . $category->getName() . '</a></li>'; ?>
<img src="<?php echo Mage::getBaseUrl('media')?>catalog/category/<?php echo $category->getThumbnail() ?>" height="100" width='100'>



<?php
endforeach;*/
?>


<?php
endforeach;
?>
</ul>
</section>
</div>
</section>
<br>
