<div class="row" style="padding:15px;">
<div class="col-md-6 mainblocks">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('featuredblock1')->toHtml() ?> 
</div>
<div class="col-md-3 mainblocks">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('featuredblock2')->toHtml() ?> 
</div>
<div class="col-md-3">
<div class="col-md-12 mainblocks">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('featuredblock3')->toHtml() ?> 
</div>
<div class="col-md-12 mainblocks">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('featuredblock4')->toHtml() ?> 
</div>
</div>
</div>
