<?php 
$enable=Mage::getStoreConfig('customblocks_options/blocksettings3/block_select3');

$link= Mage::getStoreConfig('customblocks_options/blocksettings3/block_link9');
$image=Mage::getStoreConfig('customblocks_options/blocksettings3/block_image9');
$url=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
		//$brand='<img src="'.$url.''.$image.'">';
		$brand= $url.$image;
		
?>

<style>
	.brand_banner{
	width:100%;
	height:70px;
	margin-bottom: 20px;
	background:url('<?php echo $brand;?>');
	}
</style>

<?php if($enable==1){?>
<div class="brand_banner">
</div>
<?php } ?>