<ul class="banner-carousel">
		<?php foreach ($banners as $banner):?>
				<li>
						<a href="<?php echo $banner->link ?>" title="<?php echo $banner->title ?>">
							<img title="<?php if($isShowTitle): ?><?php echo '<h3>'.$banner->title.'</h3>' ?><?php endif;?><?php if($isShowDescription): ?><?php echo '<p>'.$banner->content.'</p>' ?><?php endif;?>" src="<?php echo $imgLink.$banner->bannerimage ?>" alt="" />
						</a>
				</li>
		<?php endforeach ?>
</ul>
<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('.banner-carousel').bxSlider({
			auto: true,
			mode: 'horizontal',
			speed: <?php echo $transitionSpeedSlider ?>,
			preloadImages: 'visible', 
			pager: false,
			captions: <?php if($isShowTitle || $isShowDescription): ?> true <?php else: ?> false <?php endif;?>,
			controls:false
		});
	});
</script>
