<div class="row" style="padding:15px;">
<div class="col-md-3 mainblocks">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mainblock1')->toHtml() ?> 
</div>
<div class="col-md-3 mainblocks">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mainblock2')->toHtml() ?> 
</div>
<div class="col-md-3 mainblocks">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mainblock3')->toHtml() ?> 
</div>
<div class="col-md-3 mainblocks">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mainblock4')->toHtml() ?> 
</div>
</div>
